---
title: "Syllabus"
---

## PM 566: Introduction to Health Data Science 

**Term**: Fall 2025

**Time**: Friday 9am - 12:55pm

**Location**: SSB 114

**Units**: 4 

## Course Overview

This course serves as an introduction to data science with a focus on the acquisition and analysis of real-life data. Students will learn the tools needed to:

1. Create usable and reproducible datasets by accessing, scraping, and cleaning data
2. Conduct exploratory data analysis and visualization
3. Identify scientific questions that can be answered with a given dataset
4. Write functional code in the R programming language, build basic apps, and construct a website

## Learning Objectives

Through this course, students will become familiar with the techniques used in data science and apply them to health-related datasets. Students will learn:

- Programming in R and associated tools including Quarto, Git, and SQL
- Data visualization – selecting appropriate plots to gain insight from data
- Data collection – web scraping, data wrangling, and database management
- Exploratory data analysis – generating hypotheses while building intuition and understanding of a dataset
- Basic computational algorithms, including simulation strategies
- Building interactive tools and websites

**Prerequisite(s):** None

**Recommended Preparation:** Familiarity with programming, particularly in the R language

## Course Slides

Lecture slides presented in class are available on the course website: [https://uscbiostats.github.io/PM566/](https://uscbiostats.github.io/PM566/).

## Technological Proficiency and Hardware/Software Required 

The R language ([http://cran.r-project.org](http://cran.r-project.org)) will be used throughout the semester and we recommend using the R Studio IDE for coding ([https://posit.co/download/rstudio-desktop/](https://posit.co/download/rstudio-desktop/)). Additionally, if they do not already have one, students will be required to create a GitHub account ([https://github.com/](https://github.com/)).

## Readings and Supplementary Materials

There are no required readings for this course.

## Supplementary References

1. R Programming for Data Science, 2019. Roger Peng. [https://bookdown.org/rdpeng/rprogdatascience/](https://bookdown.org/rdpeng/rprogdatascience/)
1. R for Data Science, 2017. Garrett Grolemund and Hadley Wickham. [http://r4ds.had.co.nz/](http://r4ds.had.co.nz/)
1. Exploratory Data Analysis with R, 2020. Roger Peng. [https://bookdown.org/rdpeng/exdata/](https://bookdown.org/rdpeng/exdata/)
1. Mastering Software Development in R, 2017. Roger Peng, Sean Kross, Brooke Anderson. [https://bookdown.org/rdpeng/RProgDA/](https://bookdown.org/rdpeng/RProgDA/)
1. R Packages, 2023. Hadley Wickham and Jennifer Bryan. [https://r-pkgs.org/](https://r-pkgs.org/)
1. Modern Data Science with R, 2023. Benjamin S. Baumer, Daniel T. Kaplan, and Nicholas J. Horton. [https://mdsr-book.github.io/mdsr3e/](https://mdsr-book.github.io/mdsr3e/)

## Description and Assessment of Assignments

**Labs:** There will be weekly lab assignments which are graded for completion. Each week, there will be class time devoted to working on that week's lab. Completing the weekly labs will count as part of the overall grade.

**Homework:** There will be 4 assignments given throughout the semester, approximately every 2 weeks. Students may discuss the problems with one another, however, individual solutions must be submitted and copying will not be tolerated.

Students may earn extra credit on Homework by submitting their own data visualization for the weekly Tidy Tuesday dataset presented in class. Each week, a student can earn 5 points of extra credit, up to a total of 50 for the semester (equivalent to half of one homework assignment).

**Midterm Project:** The midterm project will be to perform a thorough exploratory analysis and write a report with preliminary findings using a real-world dataset of your choosing. The source code and PDF report will be uploaded to GitHub.

**Final Project:** The final project will be to write a report for an analysis applied to a real-world dataset of your choosing and to create a website that includes interactive visualizations to display the data and results. The source code, website files, and PDF report will be uploaded to GitHub.

## Grading Breakdown

| Assignment           | % of Grade |
|----------------------|------------|
| Labs                 | 10%        |
| Homework (4)         | 30%        |
| Midterm Project      | 25%        |
| Final Project        | 35%        |
| TOTAL                | 100%       |

## Assignment Submission Policy

All assignments must be completed in Quarto (or R Markdown) and submitted through the [GitHub Issues page](https://github.com/USCbiostats/PM566/issues) for the course. Late assignments will be penalized by 20% for each day past the due date, up to 5 days late, except when verifiable extenuating circumstances can be demonstrated.



## Schedule

As the weeks go by, consult the [Schedule Page](schedule.qmd) for more information on weekly topics, problem sets, readings, and other materials. The schedule is likely to change as we go. Links to readings, assignments, and other materials from class will be posted on that page. 

## Academic Integrity

The University of Southern California is foremost a learning community committed to fostering successful scholars and researchers dedicated to the pursuit of knowledge and the transmission of ideas. Academic misconduct is in contrast to the university’s mission to educate students through a broad array of first-rank academic, professional, and extracurricular programs and includes any act of dishonesty in the submission of academic work (either in draft or final form).  

This course will follow the expectations for academic integrity as stated in the [USC Student Handbook](https://policy.usc.edu/studenthandbook/). All students are expected to submit assignments that are original work and prepared specifically for the course/section in this academic term. You may not submit work written by others or “recycle” work prepared for other courses without obtaining written permission from the instructor(s). Students suspected of engaging in academic misconduct will be reported to the Office of Academic Integrity.

Other violations of academic misconduct include, but are not limited to, cheating, plagiarism, fabrication (e.g., falsifying data), knowingly assisting others in acts of academic dishonesty, and any act that gains or is intended to gain an unfair academic advantage.

The impact of academic dishonesty is far-reaching and is considered a serious offense against the university and could result in outcomes such as failure on the assignment, failure in the course, suspension, or even expulsion from the university.

For more information about academic integrity see the [student handbook](https://policy.usc.edu/studenthandbook/) or the [Office of Academic Integrity’s website](https://academicintegrity.usc.edu/), and university policies on [Research and Scholarship Misconduct](https://policy.usc.edu/research-and-scholarship-misconduct/).


### Statement on the use of Artificial Intelligence

Generative artificial intelligence (AI) may be used under the direction and rules specified by the course instructor in specific circumstances as outlined in the syllabus. The student is responsible for the quality and content of all written assignments. Unless otherwise indicated by the course instructor, generative AI may be used to create an initial literature review, document outline and/or to organize material toward a first draft of a class paper, proofreading, or grammatical accuracy; however the final content of the written document and critical thinking of the ideas presented in the document must represent the student’s individual work and ideas learned through course content and/or research conducted from sources outside of the generative AI system. The student must include an annotation on all materials submitted that explicitly documents how AI was used to generate the document and properly reference both the sources and the AI tools such as ChatGPT (OpenAI, 2023). The student must review the information in the document and edit for accuracy, completeness, proper grammar, and demonstrate that the wording accurately reflects the student's understanding and purpose in writing the text. Students should be aware that text generated solely from AI generators may include factual errors, bias, and may contain incomplete or inaccurate reference information, in addition to furthering appropriating knowledge produced by historically marginalized scholars without proper crediting. If you have any questions on whether a specific AI tool is allowed for any aspect of your work in this class, please ask your instructor for guidance. Failure to ensure agreement with your instructor on use of AI, prior to doing so, may result in a zero score. (NOTE: instructors have sophisticated tools to determine AI plagiarism.)

## Students and Disability Accommodations: 

USC welcomes students with disabilities into all of the University’s educational programs. The Office of Student Accessibility Services (OSAS) is responsible for the determination of appropriate accommodations for students who encounter disability-related barriers. Once a student has completed the OSAS process (registration, initial appointment, and submitted documentation) and accommodations are determined to be reasonable and appropriate, a Letter of Accommodation (LOA) will be available to generate for each course. The LOA must be given to each course instructor by the student and followed up with a discussion. This should be done as early in the semester as possible as accommodations are not retroactive. More information can be found at http://osas.usc.edu. You may contact OSAS at (213) 740-0776 or via email at osasfrontdesk@usc.edu.


## Support Systems:

*Counseling and Mental Health - (213) 740-9355 – 24/7 on call*  
[https://studenthealth.usc.edu/counseling/](https://studenthealth.usc.edu/counseling/)   
Free and confidential mental health treatment for students, including short-term psychotherapy, group counseling, stress fitness workshops, and crisis intervention. 

*National Suicide Prevention Lifeline - dial 988 – 24/7 on call*   
[http://www.suicidepreventionlifeline.org](http://www.suicidepreventionlifeline.org)  
Provides free and confidential emotional support to people in suicidal crisis or emotional distress 24 hours a day, 7 days a week. 

*Relationship and Sexual Violence Prevention Services (RSVP) - (213) 740-9355(WELL), press “0” after hours – 24/7 on call*  
[https://studenthealth.usc.edu/sexual-assault](https://studenthealth.usc.edu/sexual-assault)  
Free and confidential therapy services, workshops, and training for situations related to gender-based harm. 

*Office for Equity, Equal Opportunity, and Title IX (EEO-TIX) - (213) 740-5086*  
[http://eeotix.usc.edu](http://eeotix.usc.edu)  
Information about how to get help or help someone affected by harassment or discrimination, rights of protected classes, reporting options, and additional resources for students, faculty, staff, visitors, and applicants. 

*Reporting Incidents of Bias or Harassment - (213) 740-5086 or (213) 821-8298*  
[http://usc-advocate.symplicity.com/care_report](http://usc-advocate.symplicity.com/care_report)  
Avenue to report incidents of bias, hate crimes, and microaggressions to the Office for Equity, Equal Opportunity, and Title for appropriate investigation, supportive measures, and response.

*The Office of Student Accessibility Services (OSAS) - (213) 740-0776*  
[http://osas.usc.edu](http://osas.usc.edu)  
OSAS ensures equal access for students with disabilities through providing academic accommodations and auxiliary aids in accordance with federal laws and university policy.

*USC Campus Support and Intervention - (213) 821-4710*   
[http://campussupport.usc.edu](http://campussupport.usc.edu)  
Assists students and families in resolving complex personal, financial, and academic issues adversely affecting their success as a student.

*Diversity, Equity and Inclusion - (213) 740-2101*  
[http://diversity.usc.edu](http://diversity.usc.edu)  
Information on events, programs and training, the Provost’s Diversity and Inclusion Council, Diversity Liaisons for each academic school, chronology, participation, and various resources for students. 


*USC Emergency - UPC: (213) 740-4321, HSC: (323) 442-1000 – 24/7 on call*   
[http://dps.usc.edu, http://emergency.usc.edu](http://dps.usc.edu, http://emergency.usc.edu)  
Emergency assistance and avenue to report a crime. Latest updates regarding safety, including ways in which instruction will be continued if an officially declared emergency makes travel to campus infeasible.

*USC Department of Public Safety - UPC: (213) 740-6000, HSC: (323) 442-1200 – 24/7 on call*   
[http://dps.usc.edu](http://dps.usc.edu)  
Non-emergency assistance or information.

*Office of the Ombuds - (213) 821-9556 (UPC) / (323-442-0382 (HSC)*  
[http://ombuds.usc.edu](http://ombuds.usc.edu)    
A safe and confidential place to share your USC-related issues with a University Ombuds who will work with you to explore options or paths to manage your concern.

*Occupational Therapy Faculty Practice - (323) 442-3340* or   
otfp@med.usc.edu, [http://chan.usc.edu/otfp](http://chan.usc.edu/otfp)   
Confidential Lifestyle Redesign services for USC students to support health promoting habits and routines that enhance quality of life and academic performance. 





