---
title: "Interactive visualization and effective data communication I"
date: "2020-10-28"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required reading

You are expected to have read these items before class. Most of these linked sections/chapters are quite short.

## Interactive visualization

### Introduction to plotly: 
Please read the following sections of [Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/index.html), by Carson Sievert:

- Creating Views (Plotly features): Sections 1-3, 5-7
- Publishing Views: Sections 9-12
- Arranging and Animating Views: Sections 13-14

### Introduction to Shiny: 

- [Introduction to Interactive Documents](https://shiny.rstudio.com/articles/interactive-docs.html): provides a quick guide to getting started with Shiny.
 
## Creating websites
We will be developing a website using rmarkdown's site generator. Please read:

- [Chapter 10.5: Websites in rmarkdown’s site generator](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html) in [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/), Yihui Xie, J. J. Allaire, Garrett Grolemund

# Optional reading

## Interactive visualization
- The official [Shiny website](http://shiny.rstudio.com) includes extensive articles, tutorials, and examples.
- [Coursera course on developing data products, sessions on Shiny, GoogleVis, and Plotly](https://www.coursera.org/lecture/data-products/shiny-1-1-xgyMn)
- For an introduction to creating dashboards see: [Chapter 5: Dashboards (Layout, Components, Shiny)](https://bookdown.org/yihui/rmarkdown/dashboards.html) from [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/), which provides a guide for using **Shiny** with **flexdashboard** to create interactive documents from R Markdown

## Website development in rmarkdown
- For a helpful tutorial on creating a website using rmarkdown, see: [Creating websites in R](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html), Emily C. Zabor   
- For more advanced website creation using **blogdown** and the website generator Hugo see [Creating websites with R Markdown](https://bookdown.org/yihui/blogdown/).
- [Appendix B](https://bookdown.org/yihui/blogdown/website-basics.html#website-basics) of the **blogdown** book presents basic information about websites, such as HTML, CSS, and JavaScript.

## Data visualization best practices
- [Data Visualization: A Practical Introduction](https://kieranhealy.org/publications/dataviz/), Kieran Healy
- [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/), Claus O. Wilke
