---
title: "Final Project"
output: tufte::tufte_html
date: 2022-11-16
---

# Final Project

- Presentation (5 minutes): Wednesday November 30th, 2022

- Written report (single spaced, 6-8 pages where 3-4 pages are tables and figures): Wednesday December 7, 2022

**Learning Objective**: To apply the skills learned in
PM 566 by analyzing and interpreting a dataset of your choice.

**Narrative**: Through this project you will launch a
portfolio of data science projects that will become seminal for your job
hunt.

Using the dataset from your midterm, make sure you have
formulated a clear and concise question to answer. You will apply the
skills learned throughout the semester to answer this question.

**Deliverables**: 1) A 5-minute presentation where you
walk us through your website; 2) A written report with embedded tables
and figures that is submitted as a PDF to a final project-specific
github repository *and* as a downloadable link on your website.
Please see the checklist below for additional
details.

The report should have the following sections (elaborate
from what was written in the midterm):
**Introduction** (provide background on your
dataset and formulated question), **Methods**
(include how and where the data were acquired, how you cleaned and
wrangled the data, what tools you used for data exploration),
**Results** (provide final, publication ready
tables and figures from your analysis, refer to your website if needed),
and a brief **Conclusion and Summary** where
you describe your findings.

In your report, please do not include code (so make sure
`echo = FALSE`), unformatted output, or dataset summaries (e.g. output
from head(), str(), etc.)

## Checklist for Final Project

1.  <span dir="ltr">**Create a website** (HTML document and all the
    required files, including figures). It should feature:</span>
    
    1.  <span dir="ltr">A brief description of the project,</span>
    
    2.  <span dir="ltr">Interactive visualizations, also with a
        description so that people can understand what they are
        looking at, and</span>
    
    3.  <span dir="ltr">A link to the PDF version of the actual report
        (i.e. a link to “Download the report.”).</span>
    
    4.  <span dir="ltr">Your home page should feature no more than
        five interactive tables and figures. If you want to include
        more to showcase your skills, we request you do so by adding
        extra pages to the website. We will only evaluate the homepage
        of the website.</span>
        
        The actual analysis should be included in the PDF
        report. **The PDF report can refer to visualizations included in the
        website**.
2.  <span dir="ltr">**Upload everything**, source code, website files,
    and PDF report, to the GitHub repository.</span>

3.  <span dir="ltr">Make sure that the **website**, which is to be
    **hosted in GitHub pages**, actually **works**, i.e., figures and
    interactive visualizations are properly rendered when visiting the
    website..</span>

4.  <span dir="ltr">**Have a README.md file** in the upper level of
    the repository. This file provides general information about the
    project, like title, brief description, etc.</span>

5.  <span dir="ltr">The **README.md file links to the website**, e.g.
    https://username.github.io/pm566-project, .</span>

6.  <span dir="ltr">Have a **“data” folder** with either the data or
    instructions about how to acquire it. You should provide the
    instructions in a README.md within that folder.</span>

7.  <span dir="ltr">**(optional)** Your document is **fully
    reproducible**, meaning you don’t have paths to files not shared
    in the repository. For example, if you are loading a dataset with
    “fread,” it should be something like
    “fread(“https://data.com/dataset.csv”),” so you are directly
    using data online, or “fread(“data/dataset.csv”),” so the data
    needed has been shared on GitHub and is contained in the path
    “data/dataset.csv.”</span>

