---
title: "Lab 10 - HPC"
output: tufte::tufte_html
link-citations: yes
---

# Learning goals

In this lab, you are expected to learn/put in practice the following skills:

- Write a simulation program
- Use the parallel package to parallelize your simulation
- Run the simulation on AWS

# Part one: Yeat Another Coronavirus Simulation

During this week's lecture, we saw an example of a simulation program that models SARS-CoV2 using a bi-dimensional torus. In that example, individuals were embedded in a grid (torus), each having a total of 8 neighbors, and were For this week's lab, you will have to write a simulation program similar to that featured during the lecture and speed up it up using parallel computing.

The simulation should work under the following rules:

1. The world is the contour of a circle.

2. Each individual has two neighbors (left and right), each representing an independent opportunity of either passing or acquiring the disease.

3. As before, the probability of transmission depends on who wears a face-mask.

4. There are four possible states: susceptible, infected, recovered, and deceased.

5. Time is discrete.

6. The simulation starts with x% of individuals with the virus, with m of them willing to wear the face-mask.

The simulation program should have the following optional parameters: number of steps, the initial number of infected, and the number of people wearing the mask.

The questions are the following:

1. Using the simulation program, compute the 95% confidence interval (CI) for the number of deceased individuals under the following parameters:

  - A population of size 1,000
  
  - 10 individuals have the disease    
  
  - Half of the population wears the mask
  
  - Simulating a thousand scenarios, each with 20 time points.
  
2. What would be the 95% CI if three quarters of the population wears the face-masks?

A solution (the simulation program, actually) can be found in the website (file named sars-cov2-circle.R).

# Part 2: Speedup the simulation

Using the `paralle` R package (or any other method), speedup the simulation and measure how much faster the parallel version runs. Is it  linear speedup?

# Part 4: Using cloud computing

Using the AWS account set up for you, submit the simulation using R CMD BATCH and retrieve the results from the EC2 instance.


